cabal-version:      3.0
name:               trabalhoFinalHaskell
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             GabrielSaueressig
maintainer:         gabsauere@gmail.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

executable recsystem
    import:           warnings
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base ^>=4.18.3.0
                    , scotty
                    , aeson
                    , text
                    , req
                    , wai-cors  
                    , random
                    , http-types
    default-language: Haskell2010

test-suite tests
    type:             exitcode-stdio-1.0
    main-is:          TestMyFunctions.hs
    other-modules:    Main
    hs-source-dirs:   app
    ghc-options:      -main-is TestMain
    build-depends:    base ^>=4.18.3.0
                    , HUnit
                    , text
                    , scotty
                    , aeson
                    , req
                    , wai-cors
                    , random
                    , http-types
    default-language: Haskell2010